version: '3'
services:
  strapi:
    image: naskio/strapi
    environment:
      NODE_ENV: development # or production
      DATABASE_CLIENT: postgres
      DATABASE_NAME: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: strapi
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data